[package]
name = "practice_tooled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
rstest = "0.17.0"
serde = "1.0.159"
serde_json = "1.0.95"
